# This is a basic workflow to help you get started with Actions

name: Archive websites

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # - name: Set up R
      #   uses: r-lib/actions/setup-r@master

      # - name: Get list of websites from Wikidata
      #   run: |
      #     R -e 'install.packages("WikidataQueryServiceR")'
      #     Rscript fetch-urls-from-wikidata.R

      # change rights for bash script
      - name: Make spn.sh executable
        run: chmod a+x spn.sh

      # Run spn.sh to archive URLs
      - name: Send websites to the Internet Archive
        run: |
          # choose 10 random urls to save
          random_urls=$(sort -R "./data/urls.txt" | head -10)
          echo "Fetch those URLs: ${random_urls}"

          # save outlinks regex as variable: save only outlinks that have domain to be saved in URL
          outlinks_regex=$(cat "./data/outlinks_regex.txt")

          # start main script
          ./spn.sh \
          -a ${{ secrets.INTERNET_ARCHIVE_ACCESSKEY }}:${{ secrets.INTERNET_ARCHIVE_SECRET }} \
          -f ./logs \
          -d if_not_archived_within=2629800 \
          #-o $outlinks_regex \
          #$random_urls
          https://forummuenchen.org
      
      # spn.sh writes logging files. in order to inspect and use them, I need to commit them to the repo
      # following https://ilikekillnerds.com/2023/01/how-to-create-files-in-a-github-action-and-commit-them-to-your-repository/
      - name: "Add spn.sh log files to repository"
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add ./logs/*.log
          git commit -m "Update logs"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
